#!/bin/bash
dot="$(cd "$(dirname "$0")"; pwd)"
policy_output_path="$dot/policy"
#~/.local/bin/policy-tool -d -m $dot/../hope-policies -o $policy_output_path osv.frtos.main.cfi-heap-nop-rwx-stack
~/.local/bin/policy-tool -d -m $dot/../hope-policies -o $policy_output_path osv.frtos.main.rwx

