#!/usr/bin/python3

import os
import sys
import subprocess

from elftools.elf.elffile import ELFFile
from elftools.elf.constants import SH_FLAGS

script_path = os.path.dirname(os.path.realpath(__file__))
md_code = script_path + '/../build/md_code'

#with open('/home/eli/dover-renode-sdk/FreeRTOS-RISCV/samples/coremark/main', 'rb') as f:
with open(sys.argv[3], 'rb') as f:
     ef = ELFFile(f)
     for s in ef.iter_sections():
          if s['sh_flags'] & SH_FLAGS.SHF_EXECINSTR:
               print('{0}: 0x{1:X}'.format(s.name, s['sh_addr']))
               proc = subprocess.Popen([md_code, sys.argv[1], sys.argv[2]],
                                       stdin=subprocess.PIPE,
                                       )
               proc.communicate(s.data())
               proc.wait()

#print('\nwrite:')
#proc = subprocess.Popen(['cat', '-'],
#                        stdin=subprocess.PIPE,
#                        )
#proc.communicate(b'\tstdin: to stdin\n')
