#!/bin/bash

apt-get update

apt-get install -y \
        build-essential \
        cmake \
        libboost-dev \
        libboost-program-options-dev \
        libgflags-dev \
        libyaml-cpp-dev \
        locales \
        locales-all
